Test:
  image: katalonstudio/katalon:6.3.3
  stage: test
  services:
    - docker:dind
  script:
    - katalon-execute.sh -browserType="Chrome" -retry=0 -statusDelay=15 -testSuitePath="Test Suites/signup_monitoring"
  artifacts:
    when: always
    name: "$CI_COMMIT_REF_NAME"
    paths:
      - report/
    reports:
      junit:
      - 'report/*.xml'
